name: Build Containers

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  tests:
    uses: surveysolutions/surveysolutions/.github/workflows/tests.yml@master
    with:
      runs_on: 'ubuntu-latest'
      run_analysis: false
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  build-mobile:
    needs: [tests]
    uses: surveysolutions/surveysolutions/.github/workflows/mobile.yml@master

  build-and-push:
    needs: [build-mobile]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      BUILD_VCS_NUMBER: ${{ github.sha }}

    strategy:
      matrix:
        task: [DockerHq, DockerDesigner, DockerWebTester]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download mobile artifacts
        if: ${{ matrix.task == 'DockerHq' }}
        id: download
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: artifacts

      - name: show artifacts
        run: ls ${{ steps.download.outputs.download-path }}
      - name: Build and push Docker image
        run: ./.build.ps1 ${{ matrix.task }} -BuildNumber ${{ github.run_number }} -dockerRegistry ${{ env.REGISTRY }}/${{ github.repository }} -apkFolder "artifacts"
        shell: pwsh