name: Build All

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build Number'
        default: 'auto'
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      build_number: ${{ steps.build_number.outputs.build_number }}

    steps:
      - name: Define Build Number
        id: build_number
        shell: pwsh
        run: |
          $BuildNumber = "${{ github.event.inputs.build_number }}"
          if ($BuildNumber -eq "auto") {
            $BuildNumber = ${{ github.run_number }}
          }
          Write-Output "::set-output name=build_number::$BuildNumber"

  tests:
    uses: surveysolutions/surveysolutions/.github/workflows/tests.yml@master
    with:
      runs_on: 'ubuntu-latest'
      run_analysis: false
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  mobile:
    needs: [prepare, tests]
    runs-on: windows-latest

    strategy:
      matrix:
        task: [AndroidInterviewer, AndroidInterviewerWithMaps, AndroidSupervisor]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Build
      env:
        APP_CENTER_INTERVIEWER_DEV: ${{ secrets.APPCENTER_INTERVIEWER_KEY }}
        APP_CENTER_INTERVIEWER_PROD: ${{ secrets.APPCENTER_INTERVIEWER_KEY }} # will come with the prod value in the release environment
        APP_CENTER_SUPERVISOR_DEV: ${{ secrets.APPCENTER_SUPERVISOR_KEY }}
        APP_CENTER_SUPERVISOR_PROD: ${{ secrets.APPCENTER_SUPERVISOR_KEY }} # will come with the prod value in the release environment
        
      run: .\.build.ps1 ${{ matrix.task }} `
        -BuildNumber ${{ needs.prepare.outputs.build_number }} `
        -signapk -KeystoreAlias wbcapipublish `
        -androidKeyStore "${{ secrets.INTERVIEWER_KEYSTORE }}" `
        -KeystorePassword "${{ secrets.INTERVIEWER_KEYSTORE_PASSWORD }}" `
        -GoogleMapKey "${{ secrets.GOOGLEMAPS_KEY }}" `
        -ArcGisKey "${{ secrets.ARCGIS_KEY }}"
       
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/artifacts

  docker:
    needs: [prepare, mobile]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      BUILD_VCS_NUMBER: ${{ github.sha }}

    strategy:
      matrix:
        task: [DockerHq, DockerDesigner, DockerWebTester]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download mobile artifacts
        if: ${{ matrix.task == 'DockerHq' }}
        id: download
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: artifacts

      - name: Build and push
        shell: pwsh
        run: |
          ./.build.ps1 ${{ matrix.task }} \
            -BuildNumber ${{ needs.prepare.outputs.build_number }} \
            -dockerRegistry ${{ env.REGISTRY }}/${{ github.repository }} \
            -apkFolder "artifacts"

  installer:
    needs: [prepare, mobile]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup WIX
        run: |
          Invoke-WebRequest -Uri https://wixtoolset.org/downloads/v3.14.0.5722/wix314-binaries.zip -OutFile wix314-binaries.zip
          Expand-Archive -Path wix314-binaries.zip -DestinationPath installer/wix314-binaries

      - name: Download mobile artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: installer/artifacts

      - name: Build Headquarters
        run: ./.build.ps1 PackageHqOffline -BuildNumber ${{ needs.prepare.outputs.build_number }}

      - name: Extract HQ Package
        run: |
          New-Item "HQsources" -ItemType Directory
          Expand-Archive -Path artifacts/WB.UI.Headquarters.Offline.zip -DestinationPath "HQsources"

      - name: Build installer
        run: |
          ./installer/build/build-installation.ps1 -HQSourcePath "HQsources" -ClientPath ${{ steps.download.outputs.download-path }} 

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: WindowsInstaller
          path: ./installer/src/SurveySolutionsBootstrap/bin/Release/SurveySolutions*.exe